# Generated by Django 5.0 on 2026-01-22 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('league', models.CharField(choices=[('AL', 'American League'), ('NL', 'National League')], max_length=2)),
                ('division', models.CharField(choices=[('EAST', 'East'), ('CENTRAL', 'Central'), ('WEST', 'West')], max_length=10)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ballpark', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['league', 'division', 'order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(editable=False, max_length=255)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('IF', 'Infielder'), ('OF', 'Outfielder'), ('DH', 'Designated Hitter')], max_length=5)),
                ('bats', models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=1)),
                ('throws', models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team')),
            ],
            options={
                'ordering': ['team', 'position', 'jersey_number', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ToppsSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('brand', models.CharField(default='Topps', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'unique_together': {('year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ToppsCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_rookie', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topps_cards', to='api.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
                ('topps_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.toppsset')),
            ],
            options={
                'ordering': ['topps_set', 'card_number'],
                'unique_together': {('topps_set', 'card_number')},
            },
        ),
        migrations.CreateModel(
            name='ToppsCardVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_type', models.CharField(choices=[('BASE', 'Base'), ('PARALLEL', 'Parallel'), ('AUTO', 'Autograph'), ('RELIC', 'Relic'), ('AUTO_RELIC', 'Auto Relic')], max_length=20)),
                ('variant_name', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_one_of_one', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.toppscard')),
            ],
            options={
                'ordering': ['variant_type', 'serial_number'],
                'indexes': [models.Index(fields=['variant_type'], name='api_toppsca_variant_3993fb_idx'), models.Index(fields=['serial_number'], name='api_toppsca_serial__856d35_idx')],
            },
        ),
    ]
