# Generated by Django 5.0 on 2026-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_player_toppsset_toppscard_toppscardvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppscard',
            name='total_print',
            field=models.PositiveIntegerField(blank=True, help_text='総発行枚数（不明の場合はnull）', null=True),
        ),
    ]
