# Generated by Django 5.0 on 2026-01-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_author_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mlb_team_id',
            field=models.IntegerField(blank=True, help_text='MLB公式APIのチームID', null=True, unique=True),
        ),
    ]
