# Generated by Django 5.0 on 2026-01-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_mlb_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppscard',
            name='product_url',
            field=models.CharField(blank=True, help_text='Topps公式商品ページURL', max_length=500),
        ),
    ]
