# Generated by Django 5.0 on 2026-01-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_product_url_to_toppscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppscard',
            name='product_url_long',
            field=models.CharField(blank=True, help_text='Topps公式商品ページURL（長い形式）', max_length=500),
        ),
        migrations.AlterField(
            model_name='toppscard',
            name='product_url',
            field=models.CharField(blank=True, help_text='Topps公式商品ページURL（短い形式）', max_length=500),
        ),
    ]
