# Generated by Django 5.0 on 2026-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_product_url_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppscard',
            name='release_date',
            field=models.DateField(blank=True, help_text='カード発行日', null=True),
        ),
    ]
