# Generated by Django 5.0 on 2026-01-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_release_date_to_toppscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mlb_player_id',
            field=models.PositiveIntegerField(blank=True, help_text='MLB Stats API の選手ID', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.PositiveIntegerField(help_text='シーズン年')),
                ('stat_type', models.CharField(choices=[('hitting', 'Hitting'), ('pitching', 'Pitching')], help_text='成績タイプ（打撃/投球）', max_length=10)),
                ('games', models.PositiveIntegerField(blank=True, help_text='試合数', null=True)),
                ('at_bats', models.PositiveIntegerField(blank=True, help_text='打数', null=True)),
                ('runs', models.PositiveIntegerField(blank=True, help_text='得点', null=True)),
                ('hits', models.PositiveIntegerField(blank=True, help_text='安打数', null=True)),
                ('doubles', models.PositiveIntegerField(blank=True, help_text='二塁打', null=True)),
                ('triples', models.PositiveIntegerField(blank=True, help_text='三塁打', null=True)),
                ('home_runs', models.PositiveIntegerField(blank=True, help_text='本塁打', null=True)),
                ('rbi', models.PositiveIntegerField(blank=True, help_text='打点', null=True)),
                ('stolen_bases', models.PositiveIntegerField(blank=True, help_text='盗塁', null=True)),
                ('batting_avg', models.DecimalField(blank=True, decimal_places=3, help_text='打率', max_digits=4, null=True)),
                ('obp', models.DecimalField(blank=True, decimal_places=3, help_text='出塁率', max_digits=4, null=True)),
                ('slg', models.DecimalField(blank=True, decimal_places=3, help_text='長打率', max_digits=4, null=True)),
                ('ops', models.DecimalField(blank=True, decimal_places=3, help_text='OPS', max_digits=4, null=True)),
                ('wins', models.PositiveIntegerField(blank=True, help_text='勝利', null=True)),
                ('losses', models.PositiveIntegerField(blank=True, help_text='敗北', null=True)),
                ('era', models.DecimalField(blank=True, decimal_places=2, help_text='防御率', max_digits=5, null=True)),
                ('games_pitched', models.PositiveIntegerField(blank=True, help_text='登板試合数', null=True)),
                ('games_started', models.PositiveIntegerField(blank=True, help_text='先発試合数', null=True)),
                ('saves', models.PositiveIntegerField(blank=True, help_text='セーブ', null=True)),
                ('innings_pitched', models.DecimalField(blank=True, decimal_places=1, help_text='投球回', max_digits=5, null=True)),
                ('strikeouts', models.PositiveIntegerField(blank=True, help_text='奪三振', null=True)),
                ('walks_allowed', models.PositiveIntegerField(blank=True, help_text='与四球', null=True)),
                ('whip', models.DecimalField(blank=True, decimal_places=2, help_text='WHIP', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.player')),
            ],
            options={
                'ordering': ['-season', 'stat_type'],
                'indexes': [models.Index(fields=['season'], name='api_players_season_4e0ff5_idx'), models.Index(fields=['stat_type'], name='api_players_stat_ty_438c84_idx')],
                'unique_together': {('player', 'season', 'stat_type')},
            },
        ),
    ]
