# Generated by Django 5.0 on 2026-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_mlb_player_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppscard',
            name='mlb_game_id',
            field=models.PositiveIntegerField(blank=True, help_text='MLB Game ID（試合日のgameday ID）', null=True),
        ),
    ]
