# Generated by Django 5.0 on 2026-01-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_mlb_game_id_to_toppscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wbc_country',
            field=models.CharField(blank=True, help_text='WBC出場時の代表国', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='wbc_years',
            field=models.CharField(blank=True, help_text='WBC出場年をカンマ区切りで格納（例: 2017,2023）', max_length=50),
        ),
    ]
