# Generated by Django 5.0 on 2026-01-23 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_wbc_fields_to_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBCTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('champion', models.CharField(blank=True, max_length=100)),
                ('runner_up', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='WBCGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_pk', models.PositiveIntegerField(help_text='MLB Stats API gamePk', unique=True)),
                ('game_date', models.DateField()),
                ('away_team', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Final', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.wbctournament')),
            ],
            options={
                'ordering': ['game_date', 'game_pk'],
            },
        ),
        migrations.CreateModel(
            name='WBCRosterEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('mlb_player_id', models.PositiveIntegerField(help_text='MLB Stats API player ID')),
                ('player_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbc_roster_entries', to='api.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='api.wbctournament')),
            ],
            options={
                'ordering': ['country', 'player_name'],
                'unique_together': {('tournament', 'mlb_player_id', 'country')},
            },
        ),
    ]
