# Generated by Django 5.0 on 2026-01-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_blog_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('status', models.CharField(choices=[('NEW', '未対応'), ('IN_PROGRESS', '対応中'), ('RESOLVED', '対応済み'), ('CLOSED', '完了')], default='NEW', max_length=20, verbose_name='対応状況')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理者メモ')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
