# Generated by Django 5.0 on 2026-01-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_contact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_display_name',
            field=models.CharField(blank=True, help_text='表示用の投稿者名（未設定時はユーザー名）', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='カスタムURL（未設定時はIDを使用）', max_length=200, null=True, unique=True),
        ),
    ]
